image: jelaniwoods/appdev2023-rails-template-test-4-8-i

tasks:
  - env:
      DATABASE_URL: "postgresql://gitpod@localhost"
  - before: |
      bin/setup
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - vortizhe.simple-ruby-erb
    - aliariff.vscode-erb-beautify
